version: '3'
services:
  web:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: ${WEB_NAME}
    volumes:
      - /home/antares/code:/var/www/html
      - ./web-server/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./web-server/apache/cert:/etc/apache2/certificate
      - ./web-server/apache/conf:/etc/apache2/sites-enabled
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "3000:3000"
    environment:
      - DOCKER_API_VERSION=1.52
      - PHP_IDE_CONFIG:"serverName=docker"
  mysql:
    image: 'mysql:8.0'
    container_name: ${MYSQL_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
    restart: on-failure
    ports:
      - "3306:3306"